apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - name: nginx
        image: ip-10-101-1-161.ap-northeast-2.compute.internal/admin/nginx
        imagePullPolicy: Always
      imagePullSecrets:
      - name: registry-secret 
      tls:
      - hosts:
        - ip-10-101-1-161.ap-northeast-2.compute.internal
        secretName: ca-secret
